import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
def lush_green():
# model học máy lush green, Discriminative AI, lean CNN
    model=tf.keras.Sequential([
        tf.keras.layers.Input(shape=(224,224,3)),
# phép tính chập, học đặc điểm mạnh nhất của vùng 3x3 dựa trên w của kernel(model tự sinh)
        tf.keras.layers.Conv2D(
            filters=32,
            kernel_size=(3,3),
            padding="same",
            strides=(1,1),
            activation="relu"
#relu biến hàm tuyến tính của phép chập thành phi tuyến tính
# => học được nhiều đặc điểm phức tạp hơn khi đã loại bỏ hết đặc điểm yếu(k cần thiết)
        ),
# lọc lấy đặc điểm quan trọng nhất
        tf.keras.layers.MaxPooling2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Conv2D(
            filters=64,
            kernel_size=(3,3),
            padding="same",
            strides=(1,1),
            activation="relu"
        ),
        tf.keras.layers.MaxPooling2D(
            pool_size=(2,2)
        ),
#biến tất cả đặc điểm thành vector 1 chiều do yêu cầu đầu vào của dense
        tf.keras.layers.GlobalAveragePooling2D(),
#nối tất cả layer và các neuron từ những đặc điểm đã học về 128 đầu ra
        tf.keras.layers.Dense(
            128,
            activation="relu"
        ),
        tf.keras.layers.Dropout(0.5),
        tf.keras.layers.Dense(
            64,
            activation="relu"
        ),
#tắt ngẫu nhiên 40% neuron nhầm tránh hiện tượng học thuộc hình ảnh
        tf.keras.layers.Dropout(0.25),
        tf.keras.layers.Dense(
            4,
            activation="softmax"
#softmax chia tất cả đặc điểm theo tỉ lệ và chia đều cho các đầu ra
        )
    ])
#phương pháp học, qua cập nhật wei = gradient và backprogration và loss
    model.compile(
#người cập nhật trọng số adam(momemtum và RMSProp) dựa trên gradient mà ghi nhớ
#độ dốc từ đó tự điều chỉnh xem cập nhật w nhanh hay chậm
        optimizer="adam",
#loss tính loss dựa trên nhãn dán(chế độ hợp lí nhất khi sử dụng activation softmax)
        loss="sparse_categorical_crossentropy",
#thông số đánh giá khi train
        metrics=["accuracy"]
    )
    return model
def lush_green_1():
    model=tf.keras.Sequential([
        tf.keras.layers.Input(shape=((224,224,3))),
        tf.keras.layers.Conv2D(
            filters=32,
            kernel_size=(2,2),
            padding="same",
            activation="relu",
            strides=1,
            kernel_initializer="glorot_uniform"
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Conv2D(
            filters=64,
            padding="same",
            kernel_initializer="glorot_uniform",
            activation="relu",
            kernel_size=(2,2),
            strides=1
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Conv2D(
            activation="relu",
            filters=128,
            strides=1,
            kernel_initializer="glorot_uniform",
            kernel_size=(2,2),
            padding="same"
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(
            128,
            kernel_initializer="glorot_uniform",
            activation="relu",
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(
            64,
            activation="relu",
            kernel_initializer="glorot_uniform",
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(
            32,
            activation="relu",
            kernel_initializer="glorot_uniform"        
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(
            4,
            activation="softmax",
            kernel_initializer="glorot_uniform"
        )
    ])
    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model
def lush_green_2():
    model=tf.keras.Sequential([
        tf.keras.layers.Input(shape=((224,224,3))),
        tf.keras.layers.Conv2D(
            filters=32,
            kernel_size=(3,3),
            padding="same",
            activation="relu",
            strides=1,
            kernel_initializer="glorot_uniform"
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Conv2D(
            filters=64,
            padding="same",
            kernel_initializer="glorot_uniform",
            activation="relu",
            kernel_size=(3,3),
            strides=1
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Conv2D(
            activation="relu",
            filters=128,
            strides=1,
            kernel_initializer="glorot_uniform",
            kernel_size=(2,2),
            padding="same"
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Conv2D(
            kernel_initializer="glorot_uniform",
            kernel_size=(2,2),
            padding="same",
            activation="relu",
            filters=256,
            strides=1
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        )
        ,
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(
            256,
            kernel_initializer="glorot_uniform",
            activation="relu",
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(
            128,
            activation="relu",
            kernel_initializer="glorot_uniform",
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(
            64,
            activation="relu",
            kernel_initializer="glorot_uniform"        
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(
            4,
            activation="softmax",
            kernel_initializer="glorot_uniform"
        )
    ])
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.002)
    model.compile(
        optimizer=optimizer,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model
def lush_green_3():
    model=tf.keras.Sequential([
        tf.keras.layers.Input(shape=((224,224,3))),
        tf.keras.layers.Conv2D(
            filters=32,
            kernel_size=(3,3),
            padding="same",
            activation="relu",
            strides=1,
            kernel_initializer="glorot_uniform"
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Conv2D(
            filters=64,
            padding="same",
            kernel_initializer="glorot_uniform",
            activation="relu",
            kernel_size=(3,3),
            strides=1
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Conv2D(
            activation="relu",
            filters=128,
            strides=1,
            kernel_initializer="glorot_uniform",
            kernel_size=(2,2),
            padding="same"
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Conv2D(
            kernel_initializer="glorot_uniform",
            kernel_size=(1,1),
            padding="same",
            activation="relu",
            filters=256,
            strides=1
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        )
        ,
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(
            256,
            kernel_initializer="glorot_uniform",
            activation="relu",
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(
            128,
            activation="relu",
            kernel_initializer="glorot_uniform",
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(
            64,
            activation="relu",
            kernel_initializer="glorot_uniform"        
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(
            4,
            activation="softmax",
            kernel_initializer="glorot_uniform"
        )
    ])
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.002)
    model.compile(
        optimizer=optimizer,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model
def lush_green_4():
  model=tf.keras.Sequential([
      tf.keras.layers.Input(shape=((224,224,3))),
      tf.keras.layers.Conv2D(
          filters=32,
          kernel_size=(3,3),
          padding="same",
          activation="relu",
          strides=1,
          kernel_initializer="glorot_uniform"
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Conv2D(
          filters=64,
          padding="same",
          kernel_initializer="glorot_uniform",
          activation="relu",
          kernel_size=(3,3),
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Conv2D(
          activation="relu",
          filters=128,
          strides=1,
          kernel_initializer="glorot_uniform",
          kernel_size=(2,2),
          padding="same"
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Conv2D(
          kernel_initializer="glorot_uniform",
          kernel_size=(2,2),
          padding="same",
          activation="relu",
          filters=256,
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.GlobalAveragePooling2D(),
      tf.keras.layers.Dense(
          256,
          kernel_initializer="glorot_uniform",
          activation="relu",
      ),
      tf.keras.layers.Dense(
          128,
          activation="relu",
          kernel_initializer="glorot_uniform",
      ),
      tf.keras.layers.Dense(
          64,
          activation="relu",
          kernel_initializer="glorot_uniform"        
      ),
      tf.keras.layers.Dense(
          4,
          activation="softmax",
          kernel_initializer="glorot_uniform"
      )
  ])
  optimizer=tf.keras.optimizers.Adam(learning_rate=0.002)
  model.compile(
      optimizer=optimizer,
      loss="sparse_categorical_crossentropy",
      metrics=["accuracy"]
  )
  return model
def lush_green_5():
    model=tf.keras.Sequential([
        tf.keras.layers.Input(shape=((224,224,3))),
        tf.keras.layers.Conv2D(
            filters=32,
            kernel_size=(3,3),
            padding="same",
            activation="relu",
            strides=1,
            kernel_initializer="glorot_uniform"
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Conv2D(
            filters=64,
            padding="same",
            kernel_initializer="glorot_uniform",
            activation="relu",
            kernel_size=(3,3),
            strides=1
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Conv2D(
            activation="relu",
            filters=128,
            strides=1,
            kernel_initializer="glorot_uniform",
            kernel_size=(2,2),
            padding="same"
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        ),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Conv2D(
            kernel_initializer="glorot_uniform",
            kernel_size=(1,1),
            padding="same",
            activation="relu",
            filters=256,
            strides=1
        ),
        tf.keras.layers.MaxPool2D(
            pool_size=(2,2)
        )
        ,
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(
            256,
            kernel_initializer="glorot_uniform",
            activation="relu",
        ),
        tf.keras.layers.Dense(
            128,
            activation="relu",
            kernel_initializer="glorot_uniform",
        ),
        tf.keras.layers.Dense(
            64,
            activation="relu",
            kernel_initializer="glorot_uniform"        
        ),
        tf.keras.layers.Dense(
            4,
            activation="softmax",
            kernel_initializer="glorot_uniform"
        )
    ])
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.002)
    model.compile(
        optimizer=optimizer,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model
def lush_green_6():
  model=tf.keras.Sequential([
      tf.keras.layers.Input(shape=((224,224,3))),
      tf.keras.layers.Conv2D(
          filters=32,
          kernel_size=(3,3),
          padding="same",
          activation="relu",
          strides=1,
          kernel_initializer="glorot_uniform"
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Conv2D(
          filters=64,
          padding="same",
          kernel_initializer="glorot_uniform",
          activation="relu",
          kernel_size=(3,3),
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Conv2D(
          activation="relu",
          filters=128,
          strides=1,
          kernel_initializer="glorot_uniform",
          kernel_size=(2,2),
          padding="same"
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Conv2D(
          kernel_initializer="glorot_uniform",
          kernel_size=(2,2),
          padding="same",
          activation="relu",
          filters=256,
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.GlobalAveragePooling2D(),
      tf.keras.layers.Dense(
          204,
          kernel_initializer="glorot_uniform",
          activation="relu",
      ),
      tf.keras.layers.Dense(
          164,
          activation="relu",
          kernel_initializer="glorot_uniform",
      ),
      tf.keras.layers.Dense(
          132,
          activation="relu",
          kernel_initializer="glorot_uniform"        
      ),
      tf.keras.layers.Dense(
          4,
          activation="softmax",
          kernel_initializer="glorot_uniform"
      )
  ])
  optimizer=tf.keras.optimizers.Adam(learning_rate=0.002)
  model.compile(
      optimizer=optimizer,
      loss="sparse_categorical_crossentropy",
      metrics=["accuracy"]
  )
  return model
def lush_green_7():
  model=tf.keras.Sequential([
      tf.keras.layers.Input(shape=((224,224,3))),
      tf.keras.layers.Conv2D(
          filters=32,
          kernel_size=(3,3),
          padding="same",
          activation="relu",
          strides=1,
          kernel_initializer="glorot_uniform"
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Conv2D(
          filters=64,
          padding="same",
          kernel_initializer="glorot_uniform",
          activation="relu",
          kernel_size=(3,3),
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Conv2D(
          activation="relu",
          filters=128,
          strides=1,
          kernel_initializer="glorot_uniform",
          kernel_size=(2,2),
          padding="same"
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Conv2D(
          kernel_initializer="glorot_uniform",
          kernel_size=(1,1),
          padding="same",
          activation="relu",
          filters=256,
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.GlobalAveragePooling2D(),
      tf.keras.layers.Dense(
          204,
          kernel_initializer="glorot_uniform",
          activation="relu",
      ),
      tf.keras.layers.Dense(
          164,
          activation="relu",
          kernel_initializer="glorot_uniform",
      ),
      tf.keras.layers.Dense(
          132,
          activation="relu",
          kernel_initializer="glorot_uniform"        
      ),
      tf.keras.layers.Dense(
          4,
          activation="softmax",
          kernel_initializer="glorot_uniform"
      )
  ])
  optimizer=tf.keras.optimizers.Adam(learning_rate=0.002)
  model.compile(
      optimizer=optimizer,
      loss="sparse_categorical_crossentropy",
      metrics=["accuracy"]
  )
  return model
def lush_green_8():
  model=tf.keras.Sequential([
      tf.keras.layers.Input(shape=((224,224,3))),
      tf.keras.layers.Conv2D(
          filters=32,
          kernel_size=(3,3),
          padding="same",
          activation="relu",
          strides=1,
          kernel_initializer="glorot_uniform"
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Conv2D(
          filters=64,
          padding="same",
          kernel_initializer="glorot_uniform",
          activation="relu",
          kernel_size=(3,3),
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Conv2D(
          activation="relu",
          filters=128,
          strides=1,
          kernel_initializer="glorot_uniform",
          kernel_size=(3,3),
          padding="same"
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Conv2D(
          kernel_initializer="glorot_uniform",
          kernel_size=(3,3),
          padding="same",
          activation="relu",
          filters=256,
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.GlobalAveragePooling2D(),
      tf.keras.layers.Dense(
          256,
          kernel_initializer="glorot_uniform",
          activation="relu",
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(
          128,
          activation="relu",
          kernel_initializer="glorot_uniform",
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(
          64,
          activation="relu",
          kernel_initializer="glorot_uniform"        
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(
          4,
          activation="softmax",
          kernel_initializer="glorot_uniform"
      )
    ])
  optimizer=tf.keras.optimizers.Adam(learning_rate=0.001)
  model.compile(
    optimizer=optimizer,
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])
  return model  
def lush_green_9():
  model=tf.keras.Sequential([
      tf.keras.layers.Input(shape=((224,224,3))),
      tf.keras.layers.Conv2D(
          filters=16,
          kernel_size=(3,3),
          padding="same",
          activation="relu",
          strides=1,
          kernel_initializer="glorot_uniform"
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Conv2D(
          filters=32,
          padding="same",
          kernel_initializer="glorot_uniform",
          activation="relu",
          kernel_size=(3,3),
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Conv2D(
          activation="relu",
          filters=64,
          strides=1,
          kernel_initializer="glorot_uniform",
          kernel_size=(3,3),
          padding="same"
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Conv2D(
          kernel_initializer="glorot_uniform",
          kernel_size=(3,3),
          padding="same",
          activation="relu",
          filters=128,
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.GlobalAveragePooling2D(),
      tf.keras.layers.Dense(
          128,
          kernel_initializer="glorot_uniform",
          activation="relu",
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(
          64,
          activation="relu",
          kernel_initializer="glorot_uniform",
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(
          32,
          activation="relu",
          kernel_initializer="glorot_uniform"        
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(
          4,
          activation="softmax",
          kernel_initializer="glorot_uniform"
      )
    ])
  optimizer=tf.keras.optimizers.Adam(learning_rate=0.001)
  model.compile(
    optimizer=optimizer,
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])
  return model 
def lush_green_10():
  model=tf.keras.Sequential([
      tf.keras.layers.Input(shape=((224,224,3))),
      tf.keras.layers.Conv2D(
          filters=32,
          padding="same",
          kernel_initializer="glorot_uniform",
          activation="relu",
          kernel_size=(3,3),
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Conv2D(
          activation="relu",
          filters=64,
          strides=1,
          kernel_initializer="glorot_uniform",
          kernel_size=(3,3),
          padding="same"
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.Conv2D(
          kernel_initializer="glorot_uniform",
          kernel_size=(3,3),
          padding="same",
          activation="relu",
          filters=128,
          strides=1
      ),
      tf.keras.layers.MaxPool2D(
          pool_size=(2,2)
      ),
      tf.keras.layers.GlobalAveragePooling2D(),
      tf.keras.layers.Dense(
          128,
          kernel_initializer="glorot_uniform",
          activation="relu",
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(
          64,
          activation="relu",
          kernel_initializer="glorot_uniform",
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(
          32,
          activation="relu",
          kernel_initializer="glorot_uniform"        
      ),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(
          4,
          activation="softmax",
          kernel_initializer="glorot_uniform"
      )
    ])
  optimizer=tf.keras.optimizers.Adam(learning_rate=0.001)
  model.compile(
    optimizer=optimizer,
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])
  return model 